In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor,GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

from xgboost import XGBClassifier, XGBRegressor
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error, r2_score

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import seaborn as sns

In [2]:
df = sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### Regression Task

In [4]:
X = df.drop('tip', axis=1)
y = df['tip']

# Label Encoding for categorical features
le = LabelEncoder()
X['sex'] = le.fit_transform(X['sex'])
X['smoker'] = le.fit_transform(X['smoker'])
X['day'] = le.fit_transform(X['day'])
X['time'] = le.fit_transform(X['time'])

In [5]:
X.head()

   total_bill  sex  smoker  day  time  size
0       16.99    0       0    2     0     2
1       10.34    1       0    2     0     3
2       21.01    1       0    2     0     3
3       23.68    1       0    2     0     2
4       24.59    0       0    2     0     4

#### best model base on mean absolute error

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    'LinearRegression': LinearRegression(),
    'DecisionTreeRegressor': DecisionTreeRegressor(),
    'RandomForestRegressor': RandomForestRegressor(),
    'GradientBoostingRegressor': GradientBoostingRegressor(),
    'XGBRegressor': XGBRegressor(),
    'KNeighborsRegressor': KNeighborsRegressor(),
    'SVR': SVR()

}


model_scores = []
for name, model in models.items():
    # fit each model 
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    metric = mean_absolute_error(y_test, y_pred)
    model_scores.append((name, metric))


# select the best model based on MAE
sorted_models = sorted(model_scores, key=lambda x: x[1], reverse=False)
for model in sorted_models:
    print(f'Model: {model[0]}, MAE: {model[1]}')

Model: SVR, MAE: 0.5707097371316318
Model: LinearRegression, MAE: 0.6703807496461157
Model: XGBRegressor, MAE: 0.6721697168934103
Model: KNeighborsRegressor, MAE: 0.7262448979591837
Model: GradientBoostingRegressor, MAE: 0.7305584483781851
Model: RandomForestRegressor, MAE: 0.7625816326530612
Model: DecisionTreeRegressor, MAE: 0.8481632653061225

##### Best model base on R2

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    'LinearRegression': LinearRegression(),
    'DecisionTreeRegressor': DecisionTreeRegressor(),
    'RandomForestRegressor': RandomForestRegressor(),
    'GradientBoostingRegressor': GradientBoostingRegressor(),
    'XGBRegressor': XGBRegressor(),
    'KNeighborsRegressor': KNeighborsRegressor(),
    'SVR': SVR()

}


model_scores = []
for name, model in models.items():
    # fit each model 
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    metric = r2_score(y_test, y_pred)
    model_scores.append((name, metric))


# select the best model based on R2 score
sorted_models = sorted(model_scores, key=lambda x: x[1], reverse=True)
for model in sorted_models:
    print(f'Model: {model[0]}, R2 Score: {model[1]}')

Model: SVR, R2 Score: 0.5693326496439823
Model: LinearRegression, R2 Score: 0.4441368826121931
Model: XGBRegressor, R2 Score: 0.40884920227805865
Model: GradientBoostingRegressor, R2 Score: 0.3601079653595911
Model: KNeighborsRegressor, R2 Score: 0.3294034029001649
Model: RandomForestRegressor, R2 Score: 0.24122142682354453
Model: DecisionTreeRegressor, R2 Score: 0.04693488683722269

#### Based on mean squared error

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    'LinearRegression': LinearRegression(),
    'DecisionTreeRegressor': DecisionTreeRegressor(),
    'RandomForestRegressor': RandomForestRegressor(),
    'GradientBoostingRegressor': GradientBoostingRegressor(),
    'XGBRegressor': XGBRegressor(),
    'KNeighborsRegressor': KNeighborsRegressor(),
    'SVR': SVR()

}


model_scores = []
for name, model in models.items():
    # fit each model 
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    metric = mean_squared_error(y_test, y_pred)
    model_scores.append((name, metric))


# select the best model based on MSE
sorted_models = sorted(model_scores, key=lambda x: x[1], reverse=False)
for model in sorted_models:
    print(f'Model: {model[0]}, MSE: {model[1]}')

Model: SVR, MSE: 0.538321847289585
Model: LinearRegression, MSE: 0.6948129686287711
Model: XGBRegressor, MSE: 0.7389215578875857
Model: GradientBoostingRegressor, MSE: 0.7966677680193317
Model: KNeighborsRegressor, MSE: 0.8382265306122448
Model: RandomForestRegressor, MSE: 0.956621903469389
Model: DecisionTreeRegressor, MSE: 1.314512244897959

#### Assigment Find best model based on each metrics from above mention result using diamond dataset??

##### Hyper Parameter Tunning

In [12]:
# Create a dictionary of list of models to evaluate perfomance with hyperParameters
import numpy as np
models = {
    'LinearRegression': (LinearRegression(), {}),
    'SVR': (SVR(), {'kernel': ['rbf', 'poly','sigmoid']}),
    'DecisionTreeRegressor': (DecisionTreeRegressor(), {'max_depth': [None, 5, 10]}),
    'RandomForestRegressor': (RandomForestRegressor(), {'n_estimators': [10, 100]}),
    'KNeighborsRegressor': (KNeighborsRegressor(), {'n_neighbors': np.arange(3, 100,2)}),
    'GradientBoostingRegressor': (GradientBoostingRegressor(), {'n_estimators': [10, 100]}),
    'XGBRegressor': (XGBRegressor(), {'n_estimators': [10, 100]})
}



# train and predict each model with evaluation matrics

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

for name, (model, params) in models.items():
    pipeline = GridSearchCV(models, params, cv=5)

    pipeline.fit(X_train, y_train)

    # make prediction on each model
    y_pred = pipeline.predict(X_test)

    # print the perforaming metric
    print(name, 'MSE: ', mean_squared_error(y_pred, y_test))
    print(name, 'R2: ', r2_score(y_pred, y_test))
    print(name, 'MAE: ', mean_absolute_error(y_pred, y_test))
    print('\n')

InvalidParameterError: The 'estimator' parameter of GridSearchCV must be an object implementing 'fit'. Got {'LinearRegression': (LinearRegression(), {}), 'SVR': (SVR(), {'kernel': ['rbf', 'poly', 'sigmoid']}), 'DecisionTreeRegressor': (DecisionTreeRegressor(), {'max_depth': [None, 5, 10]}), 'RandomForestRegressor': (RandomForestRegressor(), {'n_estimators': [10, 100]}), 'KNeighborsRegressor': (KNeighborsRegressor(), {'n_neighbors': array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])}), 'GradientBoostingRegressor': (GradientBoostingRegressor(), {'n_estimators': [10, 100]}), 'XGBRegressor': (XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...), {'n_estimators': [10, 100]})} instead.

#### Assigment: How to get the best parameters of each models, write in for loop among the code, how to get the best model out of it??